# Generated by Django 4.2.4 on 2023-08-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(upload_to="photos/products"),
        ),
    ]
