# Generated by Django 4.2.4 on 2023-08-26 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_variationmanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VariationManager",
        ),
    ]
